### ISSUE TITLE
Packagist

### ISSUE THREAD

**Issue by Baachi** [vtsykun/better-oro-bundle#1]
Hey @vtsykun,

i would like to try your package, looks really promising!
But sadly it isn't listed on packagist. Would you like to publish this on packagist?

If you need any assistance just ping me.

BTW: Really cool work! :heart:

**Comment by vtsykun** [comment]
Hi @Baachi 
I submitted bundle to packagist. Also you can load a package directly from github ([vcs repositories](https://getcomposer.org/doc/05-repositories.md#vcs))
```
  "repositories": {
    "my-custom-repo": {
      "type": "vcs",
      "url": "https://github.com/vtsykun/better-oro-bundle.git"
    },
```

**Comment by Baachi** [comment]
Hey @vtsykun,

this is what i actually do, but using it on packagist is a lot easier and i think you bundle will also be a bit promoted :+1: 

Thanks!
